version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xlsx-to-ics-app
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
