version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xlsx-to-ics-app
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
